promtail:
  enabled: true
  config:
    lokiAddress: http://loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
      - docker: {}
      - json:
          expressions:
            go_span_id: go_span_id
      - labels:
          go_span_id:

loki:
  enabled: true