promtail:
  enabled: true

loki:
  enabled: true
  datasource:
    jsonData: |
      "derivedFields:
      - name: goProfileExemplar
        matcherRegex: go_span_id=(\\\\w+)
        url: ride-sharing-app.cpu{profile_id=\"$$${__value.raw}\"}
        datasourceUid: pyroscope"